version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.scripthive.com.br`)"
        - "traefik.http.routers.vaultwarden.entrypoints=websecure"
        - "traefik.http.routers.vaultwarden.tls.certresolver=cloudflare"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"
    ports:
      - "9445:80"
    volumes:
      - /root/vaultwarden/vw-data:/data:rw
    env_file:
      - /root/vaultwarden/.env.vaultwarden
    networks:
      - network_public

networks:
  network_public:
    external: true
